name: test
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python -m unittest discover test/
